# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_entrega', models.DateField(verbose_name='fecha de entrega')),
                ('estado', models.CharField(choices=[(None, 'Seleccione...'), ('iniciado', 'Iniciado'), ('incompleto', 'En proceso'), ('cancelado', 'Cancelado'), ('terminado', 'Terminado')], max_length=10)),
                ('imagen_proyecto', models.ImageField(blank=True, null=True, upload_to='img-proyectos/')),
                ('valor_proyecto', models.PositiveIntegerField(verbose_name='valor del proyecto')),
                ('progreso', models.SmallIntegerField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('empleados', models.ManyToManyField(blank=True, db_table='proyecto_has_empleado', to='empleados.Empleado', verbose_name='asignar empleados')),
            ],
            options={
                'db_table': 'proyecto',
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'tecnologia',
            },
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'tipo de Proyecto',
                'verbose_name_plural': 'Tipos de Proyectos',
                'db_table': 'tipo_proyecto',
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tecnologias',
            field=models.ManyToManyField(db_table='proyecto_has_tecnologia', to='proyectos.Tecnologia'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.ManyToManyField(db_table='proyecto_has_tipo', to='proyectos.TipoProyecto'),
        ),
    ]
