# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=400)),
                ('fecha', models.DateField(blank=True)),
            ],
            options={
                'db_table': 'evento',
            },
        ),
    ]
