-- Table: empleado
INSERT INTO empleado (user_ptr_id, telefono, direccion, fecha_nacimiento, url, profesion, perfil, foto) VALUES (1, '32423434', 'Miami, Estados Unidos, EU', '1995-04-30', 'www.osnaiderluis.com', 'Backend', 'gsdkljsdfkjsdklfsdklfsdñfksdfñosdfklñsdfsdffsdfsdfsdfsdfsdfsd', '    ');
INSERT INTO empleado (user_ptr_id, telefono, direccion, fecha_nacimiento, url, profesion, perfil, foto) VALUES (2, '2141234132', 'Cartagena, Colombia, Co', '2017-11-13', 'www.osnaider.com', 'Backend', 'smdfksdmfklsfskfsdf', '');
INSERT INTO empleado (user_ptr_id, telefono, direccion, fecha_nacimiento, url, profesion, perfil, foto) VALUES (3, '3948234654', 'Cartagena, Colombia, Co', '2017-11-14', 'www.jony.com', 'Frontend', 'fljsflsajdlsajdlakdj', '');
INSERT INTO empleado (user_ptr_id, telefono, direccion, fecha_nacimiento, url, profesion, perfil, foto) VALUES (4, '9045435098', 'New York, Estado Unidos, Dc', '2017-11-22', 'www.claudia.com', 'Administradora', 'anaksdnaksjdsajkd', '');
INSERT INTO empleado (user_ptr_id, telefono, direccion, fecha_nacimiento, url, profesion, perfil, foto) VALUES (5, '3453634534', 'Cartagena, Colombia, Co', '1995-09-12', 'www.esteban.com', 'Ing de sistemas', 'loremLorem ipsum dolor sit amet, consectetur adipisicing elit', '');
INSERT INTO empleado (user_ptr_id, telefono, direccion, fecha_nacimiento, url, profesion, perfil, foto) VALUES (6, '43534452', 'New York, Estado Unidos, Dc', '1980-09-23', 'www.cristianieto.com.co', 'Ing de software', 'Cannot set values on a ManyToManyField which specifies an', '');
INSERT INTO empleado (user_ptr_id, telefono, direccion, fecha_nacimiento, url, profesion, perfil, foto) VALUES (7, '4353453454', 'Cartagena, Colombia, Co', '1987-09-12', 'http://www.sergio.ux.com', 'Ing de sistemas', 'gdfgffdgdfgdfgdfgdfgfdgdfgdfg', '');
INSERT INTO empleado (user_ptr_id, telefono, direccion, fecha_nacimiento, url, profesion, perfil, foto) VALUES (8, '978797', 'Cartagena, Colombia, Co', '1991-09-16', 'http://www.admobla.com', 'Mercaderista', 'Soy un joven emprendedor amante a las tecnologias modernas y trabajo en HomeCenter', '');
INSERT INTO empleado (user_ptr_id, telefono, direccion, fecha_nacimiento, url, profesion, perfil, foto) VALUES (10, '2343425', 'New York, Inglaterra In', '1986-09-23', 'http://www.yao.com', 'Ingeniero de Sonido', 'fsdfdfdsfgdfhs dfhdfhs fdhdsh dhsdf hdfh dfsh dfh dfhdfshdfhsdh', '');
